jeertmans/manim-slides

.github/workflows/languagetool.yml, README.md
This gives a high upgrade to the README
=> chore(README): upgrade documentation in README

manim_slides/present.py
This changes the previous behavior that was such that going to previous presentation (scene) would start it from zero.
=> fix(cli): previous presentation starts last slide

manim_slides/present.py
As proposed in #21, it is now possible to record a presentation output to a video file, with option `--record-to="some_file.avi"`.
Closes #21
=> feat(cli): record presentation

manim_slides/config.py
This adds an error message to explain why calling `self.pause()` cannot work if no previous animation was played.
=> fix(lib): add a more meaningful error message

.pre-commit-config.yaml, docs/source/conf.py, example.py, manim_slides/defaults.py, manim_slides/manim.py, manim_slides/present.py, manim_slides/slide.py, setup.py, static/logo.py
Addresses #37
---
Need feedback on which mypy arguments are relevant.
=> chore(ci): pre-commit mypy

.github/ISSUE_TEMPLATE/documentation.yml
-  Template drafted for documentation
-  Consists of attributes for describing the issue, link to affected page, Issue type, Recommendation
- Code of conduct is also added, can keep or remove them subjected to approval
Template for Question/Help/Support is put on hold until further clarification. 
Questions :
1. Should we redirect them to a support page or design a template like the other issues ?
2. If questions based template is to be used, what is the plan to revert back to the user ?
=> Issue more templates

manim_slides/config.py, manim_slides/present.py
This adds a new option that allows to control how the video is going to be scaled. By default, we now use a smooth rescaling, but fast mode with no interpolation can be used (previously default).
=> feat(cli): add resize mode option

manim_slides/present.py
This allows to define the background color used for border when resize mode is set to "keep".
Option output with `--help`:
```console
--background-color, --bgcolor COLOR
Set the background color for borders when
using "keep" resize mode. Can be any valid
CSS color, e.g., "green", "#FF6500" or
"rgba(255, 255, 0, .5)".  [default: black]
```
Closes #52
=> feat: add option for background color

manim_slides/commons.py, manim_slides/present.py
This changes some metavars such that `--help` output is closer to the Sphinx documentation.
=> chore(cli): change metavar for some options

.flake8
This specifies the minimal python version to be check for with flake8, so that we are not annoyed with irrelevant.
=> fix(ci): setup minimal python version for flake8

.pre-commit-config.yaml
1. Remove redundant black hook introduced in 7128c01
2. Specify minimal supported python version for hooks – black & isort.
isort: 
```
--py {all,2,27,3,310,35,36,37,38,39,auto}, --python-version {all,2,27,3,310,35,36,37,38,39,auto}
Tells isort to set the known standard library based on the specified Python version.
Default is to assume any Python 3 version could be the target, and use a union of all stdlib modules across versions.
If auto is specified, the version of the interpreter used to run isort (currently: 311) will be used.
```
black:
```
-t, --target-version [py33|py34|py35|py36|py37|py38|py39|py310|py311]
Python versions that should be supported by
Black's output. [default: per-file auto-
detection]
```
=> Remove redundant black hook & specify minimal supported python version for hooks

.pre-commit-config.yaml, manim_slides/commons.py, manim_slides/config.py, manim_slides/convert.py, manim_slides/present.py, manim_slides/slide.py, manim_slides/wizard.py
=> chore(lib): add missing type hints and mypy is happy!

manim_slides/config.py
With the current version of ffmpeg on Windows, the file path in the list file must be enclosed by single quotes.
=> fix(convert): correctly quote paths when using ffmpeg on Windows

README.md, example.py, manim_slides/slide.py
This removes the constraint that required a Slide class to end with a animation. This was actually not needed, and could lead to confusion since `self.wait` is not an animation with ManimGL, but well with Manim.
This fix, however, still means that a calls to `self.wait` with ManimGL, after last `self.pause` call, will be ignored.
=> feat(lib): remove constraint on last animation and update readme

manim_slides/slide.py
This fixes a previous issue that occured when a class didn't have any `pause`
=> fix(lib): a class can now have zero slide and work

manim_slides/convert.py
Issue #128
Added an enum that controls the background-size, added 'contain' as the default value. Then, in the render generator, this enumerator is used.
=> Adding Feature Background-Size in html-slides

docs/source/reference/api.md, manim_slides/slide.py
This deprecates `pause` function in favor to `next_slide`, that will also be called by `next_section` in the future.
=> chore(lib): use `next_slide` not `pause`

docs/source/features_table.md, docs/source/index.md, docs/source/reference/sharing.md, manim_slides/convert.py, poetry.lock, pyproject.toml
You can now convert your presentations to PowerPoint
=> feat(convert): PowerPoint conversion 

manim_slides/present.py
This add new CLI features for faster slides debugging, i.e., launching slides at a precise animation / slide number.
Closes #149 (from previous commit)
Closes #150
=> feat(cli): add start at index options

manim_slides/config.py, manim_slides/convert.py, manim_slides/present.py, manim_slides/slide.py, pyproject.toml
The `present` command will now read by default the resolution of each presentation, and only change it if specified by the user.
This PR also fixes bugs introduced by #156 and previous PRs, where the transition between two presentation was not correct...
=> feat(cli): auto detect resolution

example.py, manim_slides/present.py
When a slide is replayed (either normally or reversed), its state must be reset.
Closes #161
=> fix(cli): do not terminate slides early

docs/source/reference/api.md, docs/source/reference/html.md, docs/source/reference/sharing.md, paper/paper.md
I've created this PR to collect a few suggestions from my [JOSE review](https://github.com/openjournals/jose-reviews/issues/206).
These suggestions clarify wording or fix some typos. Hope it's helpful!
=> Suggestions from JOSE review

README.md, docs/source/contributing/workflow.md
Hello @bryanwweber 
This small PR tries to address most of the comments you issued in #169.
The main concern I have with documenting the whole Manim installation procedure is that it takes quite a lot of space (because each platform has its own dependencies) and it would be hard for me to keep it up-to-date if changes happen. Therefore, a simple solution is to link to the correct installation guidelines on their respective website.
What do you think?
Closes #169
=> chore(docs): update install documentation

manim_slides/convert.py
As described in #181, there was a mismatch between the type return by `click` and the one used by `pydantic`. Now we only use `Path` types.
Closes #181
=> fix(convert): `--use-template` fixed

.github/workflows/test_examples.yml, poetry.lock, pyproject.toml
This PR proposes to update to PySide6.5.
On Ubuntu, you may face this problem (solution included): https://bugreports.qt.io/browse/PYSIDE-2306
=> chore(deps): upgrading to qt6.5

manim_slides/manim.py, manim_slides/slide.py
Improve wipe transition by using FadeIn and FadeOut. The also allows to support introducers and removers.
=> feat(lib): improve wipe animation

docs/source/reference/api.md, manim_slides/slide.py
Add a new attribute that will allow to automatically call `self.wait(...)` between two slides, to fix graphical issues.
=> feat(lib): add `wait-time-between-slides` attribute

docs/source/reference/api.md, manim_slides/slide.py
=> feat(lib): add canvas and features

tests/conftest.py, tests/test_commons.py, tests/test_defaults.py
Add new tests to improve overall coverage
=> chore(tests): test commons and defaults

.gitignore, manim_slides/config.py, manim_slides/defaults.py, manim_slides/present.py, poetry.lock, pyproject.toml, tests/test_defaults.py
This PR introduces a **BREAKING CHANGE**: the general config file is now written in the TOML format. Keys are also placed under a shared subsection. Previous config files will be ignore.
Migration from the previous format can be easily performed with `manim-slides init` and copy/pasting the key codes if necessary.
=> feat(lib): change config file from json to toml

manim_slides/slide.py
This fixes a bug that would block the process forever because FFMPEG was asking if it could overwrite or not.
=> fix(lib): check if reversed file exist

manim_slides/logger.py, manim_slides/present.py
This kinda fixes the issue of weird resizes between two presentations
=> feat(present): fix presentation size and add screen option

CHANGELOG.md, manim_slides/commons.py, manim_slides/logger.py, tests/conftest.py, tests/test_commons.py
=> chore(cli): remove unused PERF verbosity level

.github/workflows/pages.yml, CHANGELOG.md, docs/source/index.md, docs/source/reference/examples.md, manim_slides/docs/manim_slides_directive.py
You can optionally read a file instead of the Sphinx directive's content
=> feat(lib): Sphinx directive can now read files

CHANGELOG.md, manim_slides/convert.py
Add 3 new themes: dracula, dark-contrast and white-contrast.
=> chore(deps): bump RevealJS' default version to 4.6.1

manim_slides/convert.py
Using default factory function instead.
=> fix(convert): ClassVar was ignored by Pydantic

CHANGELOG.md, manim_slides/present/__init__.py, manim_slides/present/player.py
This does not work at the moment, because `setLoops(1)` does not seem to end the current loop. Instead, it finishes the current loop, and plays to more loops before `EndOfMedia` is reached.
Link to forum topic: https://forum.qt.io/topic/151450/qmediaplayer-setloops-1-finishes-current-loop-and-does-two-more-is-it-normal/2?_=1698233106574.
Closes #254
=> feat(cli): add `next-terminates-loop` CLI option

CHANGELOG.md, manim_slides/present/__init__.py, manim_slides/present/player.py
This was suggested by Discord use #dung_14424 on the Manim Discord.
=> feat(cli): added `--hide-info-window` option

README.md
=> chore(docs): warn users about #314

CHANGELOG.md, manim_slides/__main__.py, manim_slides/config.py, manim_slides/present/player.py, manim_slides/slide/base.py, manim_slides/slide/manim.py, tests/test_slide.py
Basic playback rate config options, closes #309
=> feat(lib): add playback rate config options

CHANGELOG.md, docs/source/_static/template.diff, docs/source/_static/template.html, docs/source/contributing/workflow.md, docs/source/installation.md, docs/source/reference/customize_html.md, docs/source/reference/index.md, manim_slides/docs/manim_slides_directive.py
Shows an example of custom template.
TODO:
Closes #356
=> chore(docs): document HTML custom templates

manim_slides/utils.py
This is a ( hopefully temporary) fix to #390.
Closes #390
=> chore(lib): filter out video files without video stream

CHANGELOG.md, manim_slides/config.py, manim_slides/convert.py, tests/test_convert.py
Apparently, ManimCE can produce two different animations with the same name (i.e., the same hash). As documented, ManimGL would anyway produce files with the same name, so this fix was needed.
Closes #428
=> fix(lib): prevent filename collision

CHANGELOG.md, docs/source/_static/template.html, manim_slides/templates/revealjs.html
First of all, thanks for the amazing project!
Recently, I was trying to deploy my animation to web using RevealJS where I wanted the first slide to loop. On the player, everything was working fine, but on the website, the first slide wasn't looping. When I looked at the produced `html` file, I saw this:
```html
...
<body>
<div class="reveal">
<div class="slides"><section
data-background-size='contain'
data-background-color="#181926"
data-background-video="index_assets/{very_long_asset_id}.mp4"
data-background-video-muteddata-background-video-loop>
</section></div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/5.1.0/reveal.min.js"></script>
...
```
I think there's a problem with the spacing of `data-background-video-muted` and `data-background-video-loop` [default …
=> fix(convert): Whitespace issue in default RevealJS template

CHANGELOG.md, manim_slides/config.py, tests/test_slide.py
#299 added support for stopping looping slides smoothly, at which point specifying both `loop=True` and `auto_next=True` on a `next_slide` starts making sense. There is an old validation check in the code referencing #299 that was never removed.
This functionality (on the next press, waiting for the current loop to end and then immediately proceeding to the next slide) seems to work without issues on the QT presenter. The reveal.js presenter doesn't like it as much, but it's also not supported by `--next-terminates-loop`.
=> chore(lib): Remove old validation check preventing `loop=True` with `auto_next=True`

manim_slides/present/player.py, pyproject.toml
This pull request fixes the screen going black after the video ends in versions of PySide6 v6.5.3 and newer. This allows for other errors (like #315) that require a newer version of PySide6 to also be fixed.
Closes #315 
I was attempting to get `manim-slides` to work with the new versions of PySide6, as to stop the `Device loss detected in Present()` error, and found that at the end of the video, a frame of size (-1, -1) would attempt to appear. So, to prevent this, I added a requirement that the frame should only be displayed if it is the same size as the frame before it. Upon adding, the video no longer disappeared once it ended.
=> Fix for #293 and similar errors

CHANGELOG.md, docs/source/installation.md, manim_slides/present/__init__.py, manim_slides/present/player.py, pyproject.toml, requirements-dev.lock, requirements.lock
See #464 for original pull request. I did some mistakes but by pushing on my main branch instead of @PeculiarProgrammer 's main branch.
=> fix(present): black video flashes and other bugs linked to Qt

.readthedocs.yaml, CHANGELOG.md, docs/source/reference/magic_example.ipynb, manim_slides/convert.py, manim_slides/templates/revealjs.html, pyproject.toml, tests/test_convert.py, uv.lock
=> feat(convert): allow fully offline HTML presentation

docs/source/installation.md
Fix some typos / wordings in the installation guide.
=> fix(docs): some typos

CHANGELOG.md, manim_slides/present/player.py
Issue #308 refers to the inability to reverse multiple times. I fixed this by decreasing the slide index by one if reverse was invoked twice consecutively with no next-slides in between.
More specifically, the issue mentions the following:
1. Reverse to the end of the previous slide
2. Go directly to the end of the previous slide
3. Go directly to the beginning of the previous slide
This PR fixes the first. The second option seems to be the same as the first just without the animation, so I don't think an implementation of that is needed. The third option seems to just be the back button without the animation, which I also don't think is necessary.
Closes #308 
=> feat(cli): allow multiple reverses

CHANGELOG.md, manim_slides/convert.py, manim_slides/templates/revealjs.html
When manin-slides convert multiple slides into html, it add prefix to animation file in asset directory to prevent filename collision (as https://github.com/jeertmans/manim-slides/issues/428 mentioned) but doesn't add the prefix in HTML's reference to the file.
I modified the HTML templates and pass prefix function to it.
See https://github.com/jeertmans/manim-slides/issues/496 also.
=> fix(convert): blank web page when converting multiple slides into HTML

CHANGELOG.md, docs/source/_static/template.html, docs/source/faq.md, docs/source/reference/sharing.md, manim_slides/convert.py, manim_slides/ipython/ipython_magic.py, manim_slides/templates/revealjs.html, pyproject.toml, tests/test_convert.py, tests/test_main.py
Currently, the `--offline` parameter for `convert` stores the JS and CSS files in another folder. Inline CSS and JS makes it easy to share presentations by merging everything into a single HTML file. That way, combined with `-cdata_uri=true`, you don't need to share anything more than one HTML file.
EDIT: Changed `-cdata_uri=true` to `--one_file`. Now, the combination of `--offline` and `--one_file` together pushes the CSS and JS inline.
=> feat(convert/html): inline CSS and JS with convert --one_file --offline

CHANGELOG.md, docs/source/_static/template.html, manim_slides/templates/revealjs.html
As described in https://github.com/hakimel/reveal.js/discussions/3362#discussioncomment-11733074, currently, the base64 representation of the slide is loaded "on the fly" by RevealJS, which in results in a few frames of a blank screen. This solution is only executed once and updates all videos "src" attribute at the beginning of the presentation.
=> fix(convert): avoid micro-stuttering with --one-file in HTML presentation

CHANGELOG.md, docs/source/_static/template.html, manim_slides/templates/revealjs.html
Fixes a problem introduced by #508 where lazy loaded slides by RevealJS are never loaded.
=> fix(convert): fix missing slides in HTML presentation after #508

CHANGELOG.md, manim_slides/config.py, manim_slides/slide/base.py, manim_slides/slide/manim.py, manim_slides/utils.py, tests/test_slide.py
See https://github.com/jeertmans/manim-slides/discussions/520
=> feat(lib): allow to insert external videos as slides

manim_slides/convert.py
Bump version as it includes a nice fix for speaker view: background videos are now played.
See: https://github.com/hakimel/reveal.js/pull/1037#issuecomment-1825352783.
=> chore(html): bump RevealJS version to 5.2

CHANGELOG.md, manim_slides/templates/revealjs.html
This allows to open the speaker view no matter if we had notes included.
=> feat(html): always include RevealJS' notes plugin

CHANGELOG.md, manim_slides/templates/revealjs.html
Pressing <kbd>SPACE</kbd> key now pauses the slides, instead of skipping it.
=> feat(html): pause HTML slides with `SPACE` key

CHANGELOG.md, manim_slides/render.py, tests/data/slides.py, tests/test_slide.py
Closes #544
Propagate the exit code of `manim render` when invoking `manim-slides render`.
=> feat(lib): propagate `manim render` exit code

CHANGELOG.md, docs/source/gallery.md
Add a school presentation to the example gallery
=> chore(docs): add example to gallery
