.github/workflows/python-publish.yml
manim_slides/slide.py
setup.py

This PR adds the possibility to reverse animations on the fly.

feat(cli): reverse videos on the fly!

---

manim_slides/present.py

fix(cli): resize only on fullscreen

---

docs/source/conf.py
manim_slides/present.py

fix(cli): properly rewind / previous slide after reverse

---

.github/ISSUE_TEMPLATE/feature_request.yml

Add Feature Request Template

---

manim_slides/commons.py
manim_slides/config.py
manim_slides/present.py
manim_slides/wizard.py

This PR adds basic logging support, to be extended in the future.

feat(cli): add basic logging facilities

---

.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/support.yml

Closes #42 
-  Template drafted for Question/Help/Support
-  Consists of attributes for criticality of the support and description

Support template

---

README.md
manim_slides/config.py
manim_slides/present.py
manim_slides/wizard.py
setup.py

This, hopefully, should now add support for M1 chips
Closes #53

refactor(lib): change PyQT5 to PySide6

---

README.md

```python
isinstance(venv, virtual_environment) and
isinstance(virtualenv, virtual_environment) and
venv != virtualenv
```

docs: correct virtual environment information

---

.github/workflows/test_examples.yml
setup.py

chore(python): support and tests for Python 3.11

---

.github/workflows/test_examples.yml
poetry.lock
pyproject.toml

This is an attempt to fix all CI tests.

chore(version): fixing all CI tests

---

manim_slides/present.py

As suggested by PySide6's documentation, we avoid using pixmap.scaled() on every frame, but use scaled content to resize the image. This seems to ignore ratio, explaining why we need a new option flag.

feat(cli): speedup scaling with painter scaling

---

.github/workflows/pages.yml
.github/workflows/test_examples.yml
poetry.lock
pyproject.toml

This uses poetry's dependency groups to be more rigorous about modules version.

chore(deps): add dependency groups

---

.github/workflows/pages.yml

fix(ci): build docs using poetry env

---

README.md
docs/source/reference/index.md
docs/source/reference/sharing.md
example.py

This improves the online documentation, as titled.

chore(docs): document sharing slides

---

manim_slides/convert.py

This fixes an error introduced by #133

fix(convert): relative path in HTML files

---

.github/workflows/clearcache.yml
.github/workflows/pages.yml

We must force cache clearing to save a new media/ directory

chore(ci): clear cache

---

docs/source/_static/wizard_dark.png
docs/source/_static/wizard_light.png
docs/source/conf.py
docs/source/reference/gui.md
docs/source/reference/html.md
docs/source/reference/index.md

As titled, this adds two pages to the docs

chore(docs): adding GUI and HTML documentation pages

---

manim_slides/slide.py

Manim Slides now supports when Manim or ManimGL skip rendering some animations. All non-public attributes or methods are now named with leading __

feat(render): support skipping animations

---

.github/dependabot.yml

Setup dependabot to check for new actions

chore(ci): add action dependabot checks

---

README.md
docs/source/contributing/index.md
docs/source/contributing/workflow.md

Add seeking for help and reporting an issue sections.
Closes #172

chore(docs): update contributing guidelines

---

paper/paper.md

Hello @bryanwweber,
I hope this addresses all the comments in #171.
Feel free to suggest any other change or discuss the ones I did here :-)
Closes #171

chore(paper): update statement of need

---

docs/source/reference/examples.md

In follow up to what @francescotaurone said in #185, I decided to document how one can subclass (almost) any scene.

chore(docs): document scene subclassing

---

manim_slides/commons.py
manim_slides/present.py

A very small PR to fix an error in an help message, and improve the verbosity one.

chore(cli): fix and improve help messages

---

paper/paper.md

chore(paper): add comparison section

---

docs/source/conf.py
docs/source/reference/api.md
docs/source/reference/index.md
docs/source/reference/sphinx_extension.md
manim_slides/docs/manim_slides_directive.py
manim_slides/slide.py
poetry.lock
pyproject.toml

This PR adds a new Sphinx directive, inspired by the Manim one. This directive is also used within the docs to display examples.

feat(lib/docs): add sphinx directive

---

.github/workflows/tests.yml
manim_slides/convert.py
manim_slides/data/revealjs_template.html
poetry.lock
pyproject.toml

Thanks to @t-fritsch, Manim Slides can now convert to a fully self-contained HTML presentation using base64 encoded videos!

feat(convert): support base64 encoded videos

---

.bumpversion.cfg
poetry.lock
pyproject.toml

chore(deps): remove notebook dependencies

---

CHANGELOG.md
manim_slides/convert.py
tests/test_convert.py

fix(lib): correctly format enums on Python>=3.11

---

docs/source/reference/sharing.md

Closes #268
Add information about Github template to sharing page

Add github template to sharing page

---

.github/workflows/tests.yml
tests/test_slide.py

Attempt at fixing OpenGL issue on Windows server

fix(ci): OpenGL issue on Windows server

---

.bumpversion.cfg
.github/workflows/pages.yml
CHANGELOG.md
docs/source/conf.py
manim_slides/slide/base.py

Allow to return animation instead of playing it.

feat(lib): add `return_animation` option

---

manim_slides/present/__init__.py
pyproject.toml

chore(lib): warn about non-preferred-qt-version

---

CHANGELOG.md
manim_slides/present/__init__.py
manim_slides/present/player.py

feat(cli): added separate option for info window screen

---

docs/source/installation.md

Closes #340 
Added some basic documentation on how to install manim-slides with nix.
- [ x ] The title of my pull request is a short description of the requested changes.

chore(docs): add nixpkgs installation documentation

---

manim_slides/convert.py

chore(deps): update RevealJS version to 5.1.0

---

manim_slides/convert.py
pdm.lock
pyproject.toml
tests/test_convert.py

chore(deps): remove OpenCV python

---

CHANGELOG.md
README.md
docs/source/faq.md
docs/source/index.md

chore(docs): add faq page

---

CHANGELOG.md
docs/source/faq.md
manim_slides/convert.py

fix(cli): broken `--show-config` command

---

CHANGELOG.md
docs/source/gallery.md
docs/source/index.md

chore(docs): add an Examples Gallery

---

.github/workflows/tests.yml
CHANGELOG.md
pyproject.toml

See #398 and https://github.com/samuelcolvin/rtoml/issues/74.

chore(deps): pin `rtoml==0.9.0` on Windows

---

CHANGELOG.md
manim_slides/commons.py

chore(lib): enhance error message for `--folder`

---

.github/ISSUE_TEMPLATE/bug.yml
CHANGELOG.md
manim_slides/__main__.py
manim_slides/checkhealth.py
pyproject.toml
requirements-dev.lock
requirements.lock
tests/test_checkhealth.py

feat(cli): `manim-slides checkhealth`

---

CHANGELOG.md
manim_slides/convert.py
tests/test_convert.py

feat(cli/convert): add HTML zip output

---

CHANGELOG.md
pyproject.toml
uv.lock

Closes #494
See: https://github.com/PyAV-Org/PyAV/discussions/1661

chore(deps): pin `av<14` to avoid breaking changes

---

.github/workflows/tests.yml
CHANGELOG.md
custom_config.yml
manim_slides/render.py
manim_slides/slide/manimlib.py
pyproject.toml
tests/test_slide.py
uv.lock

This bumps and fixes issues related to latest ManimGL version, as it includes breaking changes.

fix(deps): bump ManimGL>=1.7.2
